openapi: 3.0.0
info:
  title: Notes API
  version: 1.0.0
  description: 노트 CRUD를 위한 REST API

paths:
  /notes:
    post:
      summary: 노트 생성
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                tag:
                  type: string
              required:
                - title
                - content
                - tag
      responses:
        "201":
          description: 생성 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NoteResponse"

    get:
      summary: 모든 노트 조회
      responses:
        "201":
          description: 전체 노트 목록
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotesResponse"

  /notes/{tag}:
    get:
      summary: 특정 태그의 노트 조회
      parameters:
        - name: tag
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 태그별 노트 목록
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotesResponse"

  /notes/{id}:
    put:
      summary: 노트 수정
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                tag:
                  type: string
      responses:
        "200":
          description: 수정 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NoteResponse"
        "404":
          description: 노트 없음

    delete:
      summary: 노트 삭제
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: 삭제 성공
        "404":
          description: 노트 없음

components:
  schemas:
    Note:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
        tag:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
    NoteResponse:
      type: object
      properties:
        message:
          type: string
        data:
          $ref: "#/components/schemas/Note"
    NotesResponse:
      type: object
      properties:
        message:
          type: string
        data:
          type: array
          items:
            $ref: "#/components/schemas/Note"
